### ISSUE TITLE
Fees may be too low

### ISSUE THREAD

**Issue by weex** [hank/litecoin-wallet#14]
I'm hearing reports (http://forum.litecoin.net/index.php/topic,1637.0.html) that low fees on outgoing transactions composed of many small, new inputs can cause said transactions to not be confirmed by miners (not sure about clients rejecting blocks with them).

**Comment by hank** [comment]
Odd - I'll look into how to fix this soon.

**Comment by weex** [comment]
The reviews seem to show this is a significant problem. You might want to put a note to submit issues here rather than through reviews. https://play.google.com/store/apps/details?id=de.schildbach.wallet.litecoin

**Comment by hank** [comment]
Yeah I'll put some big bold text at the top of the description to warn
people.  Thanks for reporting it!

**Comment by hank** [comment]
Changed the default fee to 0.01LTC.  I sent a transaction with the new fee (and verified it showed up) and it looks like it worked.  I'm waiting for it to confirm right now.

**Comment by hank** [comment]
http://explorer.litecoin.net/tx/c4cf159bab23cba8752b696868813d7e470cebf12ecec739ab337293857d9a8b#o1

This transaction was sent from the phone after I changed the default fee to 0.01LTC.  It appeared in a block.  Version 1.05 will have this default fee, and I see no reason why it wouldn't work for everyone else.  I'm going to close this bug and release the new version.

**Comment by hank** [comment]
New version updated in Play.

**Comment by hank** [comment]
From https://code.google.com/p/bitcoinj/wiki/Limitations

> There is no fee solver, which means you either have to explicitly set a fee that may be unnecessarily high, or implement that functionality yourself. Some transactions may be rejected by the network for this reason.
