### ISSUE TITLE
Exported private key fails to be imported in litecoind, the official client

### ISSUE THREAD

**Issue by hansfbaier** [hank/litecoin-wallet#15]
Hi, I exported and decrypted my private key
and then imported in litecoind with:
./litecoin-0.6.3c-linux/bin/32/litecoind importprivkey <key> <name>
and got:
error: {"code":-5,"message":"Invalid private key"}
When I re-import a priv key from the official client,
no problems.

Otherwise, great app!
Thanks!

**Comment by hank** [comment]
Yeah the format is incompatible - it's the same as with the android bitcoin
wallet.  The export format is only meant to be imported into the app.  I
hope it's working well for you.  Let me know if you experience any other
issues!

I may take some time and attempt to write a tool that decrypts and prints
the privkey from the export when given the correct password, but I make no
guarantees!
- Erik

**Comment by hansfbaier** [comment]
With bitcoin, I can import the apps private key into electrum.
Works like a charm.

2013/4/18 hank notifications@github.com

> Yeah the format is incompatible - it's the same as with the android
> bitcoin
> wallet. The export format is only meant to be imported into the app. I
> hope it's working well for you. Let me know if you experience any other
> issues!
> 
> I may take some time and attempt to write a tool that decrypts and prints
> the privkey from the export when given the correct password, but I make no
> guarantees!
> - Erik
>

**Comment by hank** [comment]
Ah electrum will take it, eh?  Interesting.  I may have to look at the code
they use to handle that and steal it!

**Comment by hank** [comment]
Openssl works for this.

**Comment by cupsusp** [comment]
same problem with "hansfbaier"
importprivkey to litecoin-qt (official client), always error: {"code":-5,"message":"Invalid private key"}

bugs ? or some tech problems ?

**Comment by hank** [comment]
The private key version is wrong I think.  I'll fix as soon as I can, but I
am very busy at the moment.

**Comment by hank** [comment]
This is fixed now as of a couple versions ago (in FTC wallet as well).

**Comment by hansfbaier** [comment]
Great! Many thanks!

2013/8/25 hank notifications@github.com
