### ISSUE TITLE
Newest litecoin-wallet error trying to import private keys from previous version

### ISSUE THREAD

**Issue by hansfbaier** [hank/litecoin-wallet#22]
I exported my private keys in 2013-04-16,
cannot reimport into latest version (2013-12-31)
Error: com.google.litecoin.core.AddressFormatException: Mismatched version number, trying to cross networks? 128 vs 128

**Comment by hansfbaier** [comment]
I worked around it by building a new litecoinj with the export patch,
building the wallet app, and reexporting.
Then I cound re-import into the latest wallet app.
But importing the private key into the official litecoin client still fails (error -4).

**Comment by hank** [comment]
Weird - I'll take a look at that...
