### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by UngarnFCP** [hank/litecoin-wallet#24]
Once cloned when I do a 
"mvn clean install"
I got a lot of errors. 
//...

Tests run: 199, Failures: 8, Errors: 15, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] litecoinj Parent .................................. SUCCESS [1.704s]
[INFO] litecoinj ......................................... FAILURE [59.235s]
[INFO] litecoinj Tools ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:01.102s
[INFO] Finished at: Thu Feb 13 10:40:52 CET 2014
[INFO] Final Memory: 13M/46M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.9:test (default-test) on project litecoinj: There are test failures.
[ERROR]
[ERROR] Please refer to /root/Documents/litecoinj/core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :litecoinj

//...
Is anybody able to compile it without errors from the current repo?
Just if I
"mvn clean install -DskipTests" it seems to work but skipping the tests is no solution for a clean build?
Got Maven 3.1.1 from the Maven homepage and set my PATH manually...
//...
Is there a guide available on how to get litecoinj and litecoin-wallet to work on a clean Ubuntu install and get his own litecoin-address for example? The documentation actually does not helps a lot here.

**Comment by hank** [comment]
If I were you, I'd use this:
https://github.com/Litecoin-Java/bitcoin-wallet
https://github.com/Litecoin-Java/bitcoinj

**Comment by nfceek** [comment]
I'm having the same issue. A better documentation for install walk thru would be very helpful. Mvn 3.1,  JDK 7, win 8, IntelliJ community edition.
Clone litcoinj to workspace
open project pom.xml
edit config: mvn clean install -Dandroid.sdk.path=C:\PROGRA~2\Android\android-sdk\tools
Get the same errors listed above.

**Comment by hank** [comment]
I stopped maintaining this code a long time ago - see the repos referenced in my previous comment.  If you have trouble building those, make a bug in that bugtracker with the exact error output.  Thanks!

**Comment by nfceek** [comment]
Thanks for the info. I'll pull the newer versions
